apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplephpmvc-db
spec:
  selector:
    matchLabels:
      app: simplephpmvc-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: simplephpmvc-db
    spec:
      containers:
        - name: simplephpmvc-db
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: simplephpmvc-app-secret
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: simplephpmvc-app-secret
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: simplephpmvc-app-secret
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: simplephpmvc-app-configmap
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
            - name: simplephpmvc-pv-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-init-config
        - name: simplephpmvc-pv-storage
          persistentVolumeClaim:
            claimName: simplephpmvc-app-pvc
---
# Sirve la base de datos a la aplicación frontend.
apiVersion: v1
kind: Service
metadata:
  name: simplephpmvc-service
spec:
  selector:
    app: simplephpmvc-db
  ports:
    - port: 3306
      targetPort: 3306
