apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simplephpmvc-app-pvc
spec:
  resources:
    requests:
      storage: 3Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: simplephpmvc-app-volume
